# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "documents", :force => true do |t|
    t.column "name", :string, :limit => 50, :default => "", :null => false
    t.column "content", :text, :default => "", :null => false
    t.column "created_on", :timestamp
    t.column "modified_on", :timestamp
  end

end
